name:                serialization
version:             0.1.0.0
license:             
author:              "Mark Seemann"
copyright:           "2023 Mark Seemann"

extra-source-files:
- README.md

dependencies:
- base
- aeson

library:
  source-dirs: src
  ghc-options:
  - -Wall

tests:
  serialization-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - serialization
    - HUnit
    - test-framework
    - test-framework-hunit